name: Ubuntu Terminal Access via remote.it

on:
  workflow_dispatch:

jobs:
  start-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install remote.it
        run: |
          curl -L https://downloads.remote.it/cli/install.sh | sh
          echo 'export PATH=$HOME/.remoteit:$PATH' >> ~/.bashrc
          source ~/.bashrc

      - name: Create SSH user
        run: |
          sudo useradd -m cliuser
          echo "cliuser:clipassword" | sudo chpasswd
          sudo usermod -aG sudo cliuser

      - name: Start SSH Server
        run: |
          sudo apt update && sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          sudo ufw allow ssh || true

      - name: Register Device with remote.it
        run: |
          ~/.remoteit/remoteit device init --name "Ubuntu-CLI"
          ~/.remoteit/remoteit device add-service ssh 127.0.0.1 22 --name "Ubuntu SSH"
